### ISSUE TITLE
CI issue

### ISSUE THREAD

**Issue by andrewstech** [is-a-dev/register#10775]
Hello @phenax. We are currently experiencing issues with the CI where its looping and removing domains then reissuing them. This has led to some users experiencing SSL issues as the DNS keeps changing between their records and the default wildcard redirect. 

Some of the new records have taken 24+ hours to update. This is causing issues when renewing our wild card SSL certs for our custom hosting as the acme challenge record is being deleted before it gets deployed.

@wdhdev I want your thoughts here as well.

**Comment by wdhdev** [comment]
I personally think we should move from CPanel to a more reliable DNS service, even Cloudflare. Cloudflare does sometimes allow record limits to be extended so we could do that and move to Cloudflare. Cloudflare would also be much better since we could add proxy support for SSLs instead of using Lets Encrypt.

**Comment by daanschenkel** [comment]
I would suggest bunny.net dns, mainly because of their programmable dns

**Comment by phenax** [comment]
There seems to be a bug in the publish script related to the order or deletions. I've fixed it now so this shouldn't be an issue anymore. Feel free to close this issue once confirmed.

> I personally think we should move from CPanel to a more reliable DNS service

@wdhdev I don't think we've had any issues directly related to cpanel yet but I'm open to this. Let's research some good reliable services that'll be easy to maintain and compile the results in a new issue.

> Cloudflare does sometimes allow record limits

We can't rely on that. We can't in the future get to a point where cloudflare doesn't let us extend the limit on records anymore. If we want to switch, it needs to be something without any hard limits.

> I would suggest bunny.net dns, mainly because of their scriptable dns: https://docs.bunny.net/docs/getting-started

@daanschenkel Bunny.net looks like a good candidate although we'd have to manage redirections separately which shouldn't be too difficult. Can we confirm if there are any restrictions on the number of records in a zone?

**Comment by wdhdev** [comment]
> > I personally think we should move from CPanel to a more reliable DNS service
> 
> @wdhdev I don't think we've had any issues directly related to cpanel yet but I'm open to this. Let's research some good reliable services that'll be easy to maintain and compile the results in a new issue.

I know Cloudflare has been denied before, but I do feel like it would be a good option for migration as it is very reliable and their API seems to work quite well. I'm not sure whether the issues with the CI were just the CI itself or whether it was CPanel, which was why I said this. I have also heard good things about bunny.net.

Also, if you check your email, I have sent you an email regarding the Public Suffix List regarding our old application.

**Comment by daanschenkel** [comment]
> There seems to be a bug in the publish script related to the order or deletions. I've fixed it now so this shouldn't be an issue anymore. Feel free to close this issue once confirmed.
> 
> > I personally think we should move from CPanel to a more reliable DNS service
> 
> @wdhdev I don't think we've had any issues directly related to cpanel yet but I'm open to this. Let's research some good reliable services that'll be easy to maintain and compile the results in a new issue.
> 
> > Cloudflare does sometimes allow record limits
> 
> We can't rely on that. We can't in the future get to a point where cloudflare doesn't let us extend the limit on records anymore. If we want to switch, it needs to be something without any hard limits.
> 
> > I would suggest bunny.net dns, mainly because of their scriptable dns: https://docs.bunny.net/docs/getting-started
> 
> @daanschenkel Bunny.net looks like a good candidate although we'd have to manage redirections separately which shouldn't be too difficult. Can we confirm if there are any restrictions on the number of records in a zone?

As far as ive seen there is no restriction, cause you can write a script to execute on dns request, that will return something. So you dont have fixed records, but can fetch them directly from github or something. We do need to think about 404 pages, thats true, but we could probably add a fallback in the code.

**Comment by andrewstech** [comment]
@phenax Unfortunately the issue is still occuring. Some records such as mail.is-a.dev are currently down yet the file hasn't been edited in 18+ days. We are also getting reports that some new subdomains are not functioning.

We were first thinking it was the DNS propagating but now we are not sure.

**Comment by phenax** [comment]
@andrewstech Looking into this. Pause merges.

**Comment by andrewstech** [comment]
> @andrewstech Looking into this. Pause merges.

Not sure what you have done but the mail domain is working again

**Comment by phenax** [comment]
Update: Not sure why but the changes to `@.json` seem to be very problematic. Might need to research why adding the MX record on root is screwing with every other record. Fixed the issue by restoring from backup from 4th Jan, removing the changes to `@` and re-applying all records created after the 4th. So far so good. Might need to observe it for the rest of today. We can resume merging prs tomorrow if all's good.

Also @is-a-dev/maintainers, btw, let's not use an is-a.dev subdomain for the status dashboard. Because if is-a.dev is down, like it was, no one can see the status dashboard which sort of defeats the purpose.

@wdhdev I've reverted the changes to `@.json`, let's avoid changes there for now till we know why it doesn't play along.

**Comment by andrewstech** [comment]
> Update: Not sure why but the changes to `@.json` seem to be very problematic. Might need to research why adding the MX record on root is screwing with every other record. Fixed the issue by restoring from backup from 4th Jan, removing the changes to `@` and re-applying all records created after the 4th. So far so good. Might need to observe it for the rest of today. We can resume merging prs tomorrow if all's good.
> 
> Also @is-a-dev/maintainers, btw, let's not use an is-a.dev subdomain for the status dashboard. Because if is-a.dev is down, like it was, no one can see the status dashboard which sort of defeats the purpose.
> 
> @wdhdev I've reverted the changes to `@.json`, let's avoid changes there for now till we know why it doesn't play along.

Thanks for the update. If you were to add the changes to the root via the cpannel would it have the same effect. If so we could always change the script to ignore the @.json file.

**Comment by wdhdev** [comment]
> Also @is-a-dev/maintainers, btw, let's not use an is-a.dev subdomain for the status dashboard. Because if is-a.dev is down, like it was, no one can see the status dashboard which sort of defeats the purpose.

I'll do this.

> @wdhdev I've reverted the changes to `@.json`, let's avoid changes there for now till we know why it doesn't play along.

Alright, let me know if you find out why or if you can manually add the records.

**Comment by wdhdev** [comment]
@phenax Same issues are occurring once again.

> Also is-a-dev/maintainers, btw, let's not use an is-a.dev subdomain for the status dashboard. Because if is-a.dev is down, like it was, no one can see the status dashboard which sort of defeats the purpose.

I've moved the status page to https://is-a-dev.wdh.gg.

**Comment by Omxpro** [comment]
update?
